name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 144.91.79.174 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -tt root@144.91.79.174
            cd /root/WorkEnrich-Backend-Django &&
            git pull origin main &&
            pip3 install -r requirements.txt &&
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver
            exit
